language: python
sudo: false
python:
    - "2.7"
install:
    - pip install -r requirements.txt
    - pip install coveralls
script:
    - nosetests
    - coverage run test_mini_spider.py
after_success:
    coveralls

