language: python
sudo: false
python:
    - "2.7"
install:
    - pip install -r requirements.txt
    - pip install coveralls
script:
    - nosetests
    - coverage run --include=test_mini_spider.py,mini_spider_rebuild.py test_mini_spider.py
    - coverage report -m
after_success:
    coveralls --verbose

